#!/bin/bash

sudo rm -rf /usr/share/gnome-shell/extensions/smartoverview@linuxdeepin.com
sudo rm -f /usr/share/glib-2.0/schemas/linuxdeepin.dgse.smartoverview.gschema.xml
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
